server:
  servlet:
    context-path: /validacion
  port: 5002

evidente-master:
  service-name: evidente-master
  url: https://experian-validacion.free.beeceptor.com
  service-name-otp: otp-evidente-master

otp:
  codigoValidacion: 123