evidente-master:
  service-name: evidente-master
  url: https://experian-validacion.free.beeceptor.com

servicios:
  otp: https://experian-validacion.free.beeceptor.com

otp:
  codigoValidacion: 123

