evidente-master:
  service-name: evidente-master
  url: https://experian-validacion.free.beeceptor.com

servicios:
  otp: http://evidente-master-credito-consumo-dev.apps.sv-bsnc-arquitectura-openshift.itac.com.co

otp:
  codigoValidacion: 123

